# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux

julia:
  - 1

git:
  depth: false

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email: true

script: ./src/QuantumTests/runTests.sh
